version: '2'

networks:
  app-tier:
    driver: bridge

services:
  redis-server-0:
    image: 'bitnami/redis:7.0.11'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=master
    networks:
      - app-tier
    ports:
      - '6379:6379'
  redis-server-1:
    image: 'bitnami/redis:7.0.11'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-server-0
    ports:
      - '6380:6379'
    networks:
      - app-tier
    depends_on:
      - redis-server-0
  redis-server-2:
    image: 'bitnami/redis:7.0.11'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-server-0
    ports:
      - '6381:6379'
    networks:
      - app-tier
    depends_on:
      - redis-server-0
  redis-sentinel-0:
    image: 'bitnami/redis-sentinel:7.0.11'
    environment:
      - REDIS_MASTER_HOST=redis-server-0
      - REDIS_SENTINEL_QUORUM=2
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=15000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=180000
      - REDIS_SENTINEL_RESOLVE_HOSTNAMES=yes
    ports:
      - '26379:26379'
    networks:
      - app-tier
    depends_on:
      - redis-server-0
      - redis-server-1
      - redis-server-2
  redis-sentinel-1:
    image: 'bitnami/redis-sentinel:7.0.11'
    environment:
      - REDIS_MASTER_HOST=redis-server-0
      - REDIS_SENTINEL_QUORUM=2
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=15000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=180000
      - REDIS_SENTINEL_RESOLVE_HOSTNAMES=yes
    ports:
      - '26380:26379'
    networks:
      - app-tier
    depends_on:
      - redis-server-0
      - redis-server-1
      - redis-server-2
  redis-sentinel-2:
    image: 'bitnami/redis-sentinel:7.0.11'
    environment:
      - REDIS_MASTER_HOST=redis-server-0
      - REDIS_SENTINEL_QUORUM=2
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=15000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=180000
      - REDIS_SENTINEL_RESOLVE_HOSTNAMES=yes
    ports:
      - '26381:26379'
    networks:
      - app-tier
    depends_on:
      - redis-server-0
      - redis-server-1
      - redis-server-2